create table public.categories (
  id bigint generated by default as identity not null,
  name character varying null,
  description text null,
  created_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;

insert into "public"."categories" ("name", "description", "created_at") values ('Food', 'Semua jenis makanan', '2026-01-28 08:00:00+00'), ('Snacks', 'Camilan ringan', '2026-01-28 08:00:00+00'), ('Beverages', 'Minuman', '2026-01-28 08:00:00+00'), ('Seasoning', 'Bumbu dan saus', '2026-01-28 08:00:00+00'), ('Dairy & Eggs', 'Susu, Keju, Yogurt, Telur', '2026-01-28 09:57:46.426932+00');

create table public.products (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null,
  price integer null,
  stock integer null,
  category_id bigint not null,
  constraint product_pkey primary key (id),
  constraint fk_products_category_id foreign KEY (category_id) references categories (id) on delete CASCADE
) TABLESPACE pg_default;

insert into "public"."products" ("created_at", "name", "price", "stock", "category_id") values ('2026-01-27 13:18:27.558298+00', 'Indomie Rebus', '3500', '10', '1'), ('2026-01-27 13:18:50.660861+00', 'Vit 1000ml', '3000', '40', '3'), ('2026-01-27 13:19:23.428699+00', 'Kecap', '12000', '20', '4'), ('2026-01-28 09:52:48.015086+00', 'Fanta', '4500', '15', '3');

create index IF not exists idx_products_category_id on public.products using btree (category_id) TABLESPACE pg_default;

create table public.transactions (
  id bigint generated by default as identity not null,
  total_amount integer not null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint transactions_pkey primary key (id)
) TABLESPACE pg_default;

create table public.transaction_details (
  id bigint generated by default as identity not null,
  transaction_id bigint null,
  product_id bigint null,
  quantity integer not null,
  subtotal integer not null,
  constraint transactions_details_pkey primary key (id),
  constraint transactions_details_product_id_fkey foreign KEY (product_id) references products (id),
  constraint transactions_details_transaction_id_fkey foreign KEY (transaction_id) references transactions (id) on delete CASCADE
) TABLESPACE pg_default;